/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.12.4.
 * To regenerate, run `npx convex codegen`.
 * @module
 */

import type { ApiFromModules } from "convex/api";
import type * as actions_openai from "../actions/openai";
import type * as listArticles from "../listArticles";
import type * as listMessages from "../listMessages";
import type * as sendArticle from "../sendArticle";
import type * as sendMessage from "../sendMessage";

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This type should be used with type-parameterized classes like
 * `ConvexReactClient` to create app-specific types.
 */
export type API = ApiFromModules<{
  "actions/openai": typeof actions_openai;
  listArticles: typeof listArticles;
  listMessages: typeof listMessages;
  sendArticle: typeof sendArticle;
  sendMessage: typeof sendMessage;
}>;
